### ISSUE TITLE
Please add cellar doors

### ISSUE THREAD

**Issue by podostro** [Jods-GH/AutoDoors#4] opened 2023-11-11 15:10 UTC
### Is your feature request related to a problem? Please describe.

No problem, just a desired feature

### Describe the solution you'd like

Please add auto open/close to cellar, large cellar and behemoth cellar doors

**Comment by Jodsderechte** [comment] 2023-11-15 22:31
Duplicate of #2 please add further info there.

**Closed by Jodsderechte** 2023-11-15 22:31 UTC
Labels: enhancement
